### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/community#15]
The roadmap.md file is super out of date. We should update the file to show the community what we think might be coming as well as to allow for folks to add their 2 cents to the roadmap to add what they'd like to see in Contour in the future.

**Comment by OrlinVasilev** [comment]
Just to keep track : https://github.com/projectcontour/community/pull/16

**Comment by youngnick** [comment]
This has been updated twice, I'm going to close out this issue. The plan is to update the roadmap after each release, since releases are now quarterly.
