### ISSUE TITLE
maintainers: Promote Tero Saarni maintainer

### ISSUE THREAD

**Issue by OrlinVasilev** [projectcontour/community#18]
This issue holds the voting process to promote him to a maintainer.

Current maintainers, please indicate your approval of this with a comment on this issue.

**Comment by youngnick** [comment]
Solidly approved, will be great to have you @tsaarni!

**Comment by skriss** [comment]
:+1: +1 from me!

**Comment by youngnick** [comment]
That's 4/5 current maintainers, so we've passed the bar. Welcome @tsaarni! @OrlinVasilev, we can go ahead with the change PR now.

**Comment by tsaarni** [comment]
Thank you for the vote of confidence! ❤️

I was mentioning to @OrlinVasilev in another discussion that I've learnt so much from you while working on Contour. I'm looking forward to continue doing that in the future! Thanks for being awesome! :)
