### ISSUE TITLE
Promote Orlin Vasilev (@Orlix) to maintainer

### ISSUE THREAD

**Issue by youngnick** [projectcontour/community#20]
Orlin is employed as the community manager for Contour, and his role requires him to be a maintainer. He's already made a number of significant contributions, so I'm happy to sponsor him.

Maintainers, please vote on this issue with a +1 comment or a reaction.

**Comment by sunjayBhatia** [comment]
+1

**Comment by xaleeks** [comment]
+1

**Comment by youngnick** [comment]
After discussion on #23, we're going to define a "SIG Community Management", that @xaleeks and @OrlinVasilev will be able to fit into. I'll update #23 with a description of the new roles there, and add in some additional intermediate roles.

**Comment by youngnick** [comment]
This was done in effect by #25, which established SIG-Contribex and SIG-Docs and made Orlin a lead of both.
