### ISSUE TITLE
REQUEST: New membership for @izturn

### ISSUE THREAD

**Issue by izturn** [projectcontour/community#33]
Hi group:
    Thanks for @skriss  @sunjayBhatia and other's help, I had sent & merged some PRs for `contour`, I enjoy in the fantasy community
    May I be a member of the `Contour Group`? I had read the all docs about `community`, but can't find an application template, so I am sorry for using the template for `Bug report`.
    Thanks for the wonder projects.

**Comment by sunjayBhatia** [comment]
Hey @izturn I just resent an invite to join the organization since I think a previous invite expired

Thanks again for the contributions! 🙏🏽

**Comment by izturn** [comment]
thx, I missed that email, :(
