### ISSUE TITLE
REQUEST: New membership for @yangyy93

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/community#37]
Hi,team:
    
I'm @yangyy93 and I've done some PR contribution work. The contour community is very active, and the community members are very nice. Thanks for @skriss @sunjayBhatia  and other's help. I want to apply to become a member of contour. I will continue to contribute to the community in the future.

**Comment by skriss** [comment]
@yangyy93 absolutely, my apologies for not having already invited you! I just sent the invite. Thanks for all your contributions to date!

**Comment by yangyy93** [comment]
thanks,I will continue to participate in the contribution of the contour community
