### ISSUE TITLE
REQUEST: New membership for @yulng

### ISSUE THREAD

**Issue by yulng** [projectcontour/community#39]
I'd like to request membership of Contour org, I will continue to contribute and join some disscusions in issues, thanks for your accept.😄😄

Merged:https://github.com/projectcontour/contour/pull/5132

**Comment by skriss** [comment]
Hi @yulng, thanks for your interest in our project! Typically, we extend org membership to contributors once they've submitted 2-3 pull requests that include bug fixes and/or features. I'd encourage you to keep contributing and look for issues that fall into the above categories (help-wanted or good first issue labels are a good place to start). Thanks again!

**Comment by yulng** [comment]
Thanks,I will submit several more PRs when I have time
