### ISSUE TITLE
maintainers: Promote Alex Xu to maintainer

### ISSUE THREAD

**Issue by youngnick** [projectcontour/community#8]
Alex Xu (@xaleeks) has become the VMware product manager for Contour. This issue holds the voting process to promote him to a maintainer.

This is a little different than normal, as we missed doing the proper governance previously. That's on us as the current maintainers, and we apologise for it.

Current maintainers, please indicate your approval of this with a comment on this issue.

**Comment by youngnick** [comment]
Obviously, I approve.

**Comment by jpeach** [comment]
+1

**Comment by skriss** [comment]
I approve.

**Comment by youngnick** [comment]
Okay, three of the previous maintainers have approved, that's a supermajority, I'll call this done. In the future, we'll leave these open for a few days.
